version: "3"

services:

  dotobot:
    image: ghcr.io/samvdkris/dotobot
    build: .
    volumes:
      - ./src:/home/worker/app
      - ./storage:/home/worker/storage
    environment:
      - TOKEN=${TOKEN}
      - DISCORD_INVITE=${DISCORD_INVITE}
      - PREFIX=${PREFIX}
