version: "3"

services:

  dotobot:
    image: ghcr.io/juliavdkris/dotobot
    build: .
    volumes:
      - ./src:/root/app
      - ./storage:/usr/src/app/storage-override
    environment:
      - TOKEN=${TOKEN}
      - DISCORD_INVITE=${DISCORD_INVITE}
      - PREFIX=${PREFIX}
