version: "3"

services:

  dotobot:
    image: ghcr.io/juliavdkris/dotobot
    volumes:
      - storage:/root/storage
    environment:
      - TOKEN=${TOKEN}
      - DISCORD_INVITE=${DISCORD_INVITE}
      - PREFIX=${PREFIX}

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30


# Weird volume fuckery. It works.
volumes:
  storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'storage'
