version: "3"

services:

  dotobot:
    image: ghcr.io/samvdkris/dotobot
    build: .
    restart: always
    volumes:
      - ./src:/home/worker/app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_INVITE=${DISCORD_INVITE}
      - PREFIX=${PREFIX}
